name: Woocommerce Coding Standards Check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.php'

jobs:
  coding-standards:
    name: Check Woocommerce Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Create Temporary composer.json
        run: |
          echo '{
            "name": "cedcoss/woocommerce-etsy-integration",
            "type": "project",
            "config": {
                "platform": {},
                "preferred-install": "dist",
                "sort-packages": true,
                "allow-plugins": {
                    "dealerdirect/phpcodesniffer-composer-installer": true
                }
            }
          }' > composer.json
      - name: Install Composer Dependencies
        run: composer install

      - name: Install PHP_CodeSniffer and WooCommerce Sniffs
        run: |
          composer require squizlabs/php_codesniffer
          composer require woocommerce/woocommerce-sniffs
      # - name: Run PHPCS with WooCommerce Sniffs
      #   run: ./vendor/bin/phpcs --warning-severity=0 --ignore-annotations --extensions=php,html --standard=WooCommerce-Core,Woocommerce,WordPress,WordPress-core .

      - name: Run PHPCS and generate report
        id: phpcs
        run: |
          if ./vendor/bin/phpcs --report=json --standard=WooCommerce-Core,Woocommerce,WordPress,WordPress-core ${{ github.event.before }}..${{ github.sha }} --extensions=php,html --status -s > phpcs-report.json; then
            echo "PHPCS passed" > phpcs-status.txt
          else
            echo "PHPCS failed" > phpcs-status.txt
          fi
          echo "PHPCS_STATUS=$(cat phpcs-status.txt)" >> $GITHUB_ENV
 
      - name: Parse PHPCS Report
        id: parse-report
        run: |
          echo "report=$(jq -r '.status' phpcs-report.json)" >> $GITHUB_ENV
      - name: Comment on PR with PHPCS errors
        if: env.PHPCS_STATUS == 'failed'
        uses: actions/github-script@v6
        with:
          github-token: "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"
          script: |
            const report = JSON.parse('${{ steps.parse-report.outputs.report }}');
            const annotations = report.files.flatMap(file =>
              file.messages.map(message => ({
                path: file.filename,
                start_line: message.line,
                end_line: message.line,
                annotation_level: 'failure',
                title: message.source,
                message: message.message
              }))
            );
            
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'COMMENT',
              body: 'Woocommerce coding standards check results:',
              comments: annotations
            });
